version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FIREBASE_BUCKET=your-project.appspot.com
      - FIREBASE_DB_URL=https://your-project.firebaseio.com
    volumes:
      - ./backend:/app

